Strategy execution
bitfinexcom/bfx-hf-models pull request #24
Opened 2022-04-26 12:48 UTC by avsek477

### Description:
Add model for saving strategy execution results.

### Breaking changes:
- [ ]

### New features:
- [ ]

### Fixes:
- [ ]

### PR status:
- [ ] Version bumped
- [ ] Change-log updated
- [ ] Tests added or updated
- [ ] Documentation updated

2022-05-04 11:02 UTC, tarcisiozf requested changes

2022-05-04 11:02 UTC, tarcisiozf commented on test/strategyExecution.js
> +  symbol: "tMATIC:USD",
lint is failing for this file

2022-05-12 11:19 UTC, tarcisiozf approved these changes
lgtm

2022-05-17 18:32 UTC, vigan-abd approved these changes

2022-05-17 18:32 UTC, merged